---
- name: Add Users to a VM
  hosts: all

  roles:
  - role: whoami

  tasks:
  - name: Add user
    user:
      name: "{{ user_name }}"
      state: present
      comment: "{{ user_comment|default(omit) }}"
      append: "{{ user_append|default(omit) }}"
      groups: "{{ user_groups|default(omit) }}"
      shell: "{{ user_shell|default('bin/bash') }}"
    become: true
  - name: Add pubkey to user
    authorized_key:
      user: "{{ user_name }}"
      state: present
      key: "{{ user_pubkey }}"
    become: true
    when:
      - user_pubkey is defined