---
- name: Deploy an OpenStack Server
  hosts: localhost
  vars:
    instance_name: testing_os_server
    instance_image: Oracle Linux 8 EPEL
    instance_key: icds-key
    instance_flavor: m5.2xlarge
    instance_network: icds-tenant-net
    os_timeout: 200
    manageiq_validate_certs: false
  vars_files:
    - cloud.yml

  roles:
  - manageiq.manageiq_vmdb

  tasks:
  - name: Display manageiq connection
    debug:
      var: manageiq_connection
  - name: Display manageiq information
    debug:
      var: manageiq
  - name: Get a vmdb object
    manageiq_vmdb:
      href: "{{ manageiq.service }}"
    register: service_object
  - name: Print the service details
    debug:
      msg: "Services object is {{ service_object }}"
  - name: Deploy server
    os_server:
      name: "{{ instance_name }}"
      state: present
      cloud: "{{ os_cloud }}"
      image: "{{ instance_image }}"
      key_name: "{{ instance_key }}"
      timeout: "{{ os_timeout }}"
      flavor: "{{ instance_flavor }}"
      nics:
        - net-name: "{{ instance_network }}"
    register: vm_object
  - debug:
      var: vm_object
  - set_fact:
      vm_href: "{{ vm_object.json.resources[0].href }}"
  - name: Add the VM to the service
    manageiq_vmdb:
      vmdb: "{{ service_object }}"
      action: add_provider_vms
      data:
        resource:
          href: "{{ vm_href }}"