---
- name: Install packages on a VM
  hosts: all
  vars:
    packages: from_playbook
  tasks:
  - name: Install packages
    package:
      name: "{{ packages.split('\n') }}"
      state: present
    become: true