---
- name: Install a package on a VM
  hosts: all
  vars:
    package: from_playbook
  tasks:
  - name: Install the package
    package:
      name: "{{ package }}"
      state: installed
    become: true