---
- name: 
  hosts: all
  gather_facts: yes
  vars:
    gcp_user: cloud-user
    gcp_group: cloud-user
    gcli_support_pkgs:
      - python3
      - python3-pip
      - python3-virtualenv
      - python3-devel
    gcli_pip_pkgs:
      - globus-cli

  tasks:
  - name: Install globus support packages
    package:
      name: "{{ gcli_support_pkgs }}"
      state: installed
    become: true
  - name: Install globus cli
    pip:
      name: "{{ gcli_pip_pkgs }}"
      state: present
      virtualenv: "/home/{{ gcp_user }}/.globusvenv"
      virtualenv_command: virtualenv-3
    become: true
    become_user: "{{ gcp_user }}"