---
- name: 
  hosts: all
  gather_facts: yes
  vars:
    gcp_user: cloud-user
    gcp_group: cloud-user
    gcli_support_pkgs:
      - python3
      - python3-pip
      - python3-devel
      - python3-setuptools
      - python39
      - python39-pip
      - python39-devel
      - python39-setuptools
    gcli_pip_pkgs:
      - globus-cli
    gcli_venv_name: 'globusvenv'
    home_path: /home

  tasks:
  - name: Install globus support packages
    package:
      name: "{{ gcli_support_pkgs }}"
      state: installed
    become: true

  - name: Install updated virtualenv
    pip:
      name: virtualenv
      state: present
      executable: pip-3.9
    become: true
    become_user: "{{ gcp_user }}"

  - name: Install globus cli
    pip:
      name: "{{ gcli_pip_pkgs }}"
      state: present
      virtualenv: "{{ home_path }}/{{ gcp_user }}/.{{ gcli_venv_name }}"
      virtualenv_command: virtualenv
      virtualenv_python: python3.9
    become: true
    become_user: "{{ gcp_user }}"

  - name: Place globus login script
    template:
      src: templates/globuslogin.sh.j2
      dest: "{{ home_path }}/{{ gcp_user }}/globuslogin.sh"
      owner: "{{ gcp_user }}"
      group: "{{ gcp_group }}"
      mode: '0750'
    become: true