---
- name: 
  hosts: all
  gather_facts: yes
  vars:
    gcli_pip_pkgs:
      - globus-cli
    gcli_venv_name: 'globusvenv'
    home_path: /home

  tasks:
  - name: Include OS-specific variables
    include_vars: "vars/{{ ansible_os_family }}.yml"

  - name: Include OS-version-specific variables
    include_vars: "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

  - name: Install globus support packages
    package:
      name: "{{ gcli_support_pkgs }}"
      state: present
    become: true

  - name: Install updated virtualenv
    pip:
      name: virtualenv
      state: present
      executable: "{{ gcli_pip_exec }}"
    become: true
    become_user: "{{ gcp_user }}"

  - name: Install globus cli
    pip:
      name: "{{ gcli_pip_pkgs }}"
      state: present
      executable: "{{ gcli_pip_exec }}"
      virtualenv: "{{ home_path }}/{{ gcp_user }}/.{{ gcli_venv_name }}"
      virtualenv_command: virtualenv
      virtualenv_python: "{{ gcli_python_exec }}"
    become: true
    become_user: "{{ gcp_user }}"

  - name: Place globus login script
    template:
      src: templates/globuslogin.sh.j2
      dest: "{{ home_path }}/{{ gcp_user }}/globuslogin.sh"
      owner: "{{ gcp_user }}"
      group: "{{ gcp_group }}"
      mode: '0750'
    become: true